### ISSUE TITLE
[Bug] Crashes when you start streaming a livestream - Android 7

### ISSUE THREAD

**Issue by Sven792** [twireapp/Twire#361]
Version used: 2.10.3 from F-Droid

With Twire on two Android 7 devices it crashes every time if you click on a livestream. Twire also crashes when you try to watch VODs. Probably related to #358?

**Comment by Sven792** [comment]
Commit e0e7c18f396aed7ab4348d7e6ccb4d3355f4d13f (description: Improve picture in picture transition) seems to be the first bad commit that introduces this bug at least for Android 7.1.1 if I'm right (I didn't really test another Android version.) It isn't a problem on (emulated) Android 8.0 though.
Crash report with the "bad" commit up to v2.10.3 (almost the same report between devices and development versions):
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.perflyst.twire.debug, PID: 3370
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/PictureInPictureParams$Builder;
        at com.perflyst.twire.fragments.StreamFragment.onSurfaceSizeChanged(StreamFragment.java:656)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$maybeNotifySurfaceSizeChanged$28(ExoPlayerImpl.java:2524)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda24.invoke(D8$$SyntheticClass)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:226)
        at com.google.android.exoplayer2.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2523)
        at com.google.android.exoplayer2.ExoPlayerImpl.access$1800(ExoPlayerImpl.java:102)
        at com.google.android.exoplayer2.ExoPlayerImpl$ComponentListener.surfaceChanged(ExoPlayerImpl.java:2876)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:630)
        at android.view.SurfaceView.setVisibility(SurfaceView.java:265)
        at com.google.android.exoplayer2.ui.StyledPlayerView.setVisibility(StyledPlayerView.java:535)
        at com.perflyst.twire.fragments.StreamFragment$10.onTransitionEnd(StreamFragment.java:1139)
        at android.transition.Transition.end(Transition.java:1924)
        at android.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:369)
        at android.transition.Transition.end(Transition.java:1924)
        at android.transition.Transition$3.onAnimationEnd(Transition.java:1875)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.PictureInPictureParams$Builder" on path: DexPathList[[zip file "/data/app/com.perflyst.twire.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.perflyst.twire.debug-2/lib/x86, /data/app/com.perflyst.twire.debug-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.perflyst.twire.fragments.StreamFragment.onSurfaceSizeChanged(StreamFragment.java:656) 
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$maybeNotifySurfaceSizeChanged$28(ExoPlayerImpl.java:2524) 
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda24.invoke(D8$$SyntheticClass) 
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281) 
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190) 
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass) 
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211) 
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:226) 
        at com.google.android.exoplayer2.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2523) 
        at com.google.android.exoplayer2.ExoPlayerImpl.access$1800(ExoPlayerImpl.java:102) 
        at com.google.android.exoplayer2.ExoPlayerImpl$ComponentListener.surfaceChanged(ExoPlayerImpl.java:2876) 
        at android.view.SurfaceView.updateWindow(SurfaceView.java:630) 
        at android.view.SurfaceView.setVisibility(SurfaceView.java:265) 
        at com.google.android.exoplayer2.ui.StyledPlayerView.setVisibility(StyledPlayerView.java:535) 
        at com.perflyst.twire.fragments.StreamFragment$10.onTransitionEnd(StreamFragment.java:1139) 
        at android.transition.Transition.end(Transition.java:1924) 
        at android.transition.TransitionSet$TransitionSetListener.onTransitionEnd(TransitionSet.java:369) 
        at android.transition.Transition.end(Transition.java:1924) 
        at android.transition.Transition$3.onAnimationEnd(Transition.java:1875) 
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153) 
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313) 
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146) 
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java) 
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
        at android.view.Choreographer.doFrame(Choreographer.java:618) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

Reverting this commit for v2.10.3 makes it work fine again. (watching livestreams and VODs is possible)

**Comment by zeropi2021** [comment]
> Version used: 2.10.3 from F-Droid
> 
> With Twire on two Android 7 devices it crashes every time if you click on a livestream. Twire also crashes when you try to watch VODs. Probably related to #358?

It looks like the same bug as mine.

**Comment by JaegerFox** [comment]
this also happens in Android 6

**Comment by samfundev** [comment]
Sorry about not catching this before the release. I'm going to do another release soon to address bugs in the last release.
